name: Rlease PDF files
on:
  push:
    tags:
      - "v*"

jobs:
  release-pdf:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v1
        with:
          version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Make and release
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xe
          docker-compose build
          docker-compose run asciidoctor make pdf
          mkdir -p dist
          cp out/pdf/*.pdf dist/

          export PUSH_EVENT_REF=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
          if [ "$(echo $PUSH_EVENT_REF | grep refs/tags/ | wc -l)" = "0" ]; then
            echo "ref is not a tag: ${PUSH_EVENT_REF}"
            exit 1
          fi
          export TAGNAME=$(echo $PUSH_EVENT_REF | sed -e 's!refs/tags/!!g')

          export GOPATH=`go env GOPATH`
          go get -u github.com/tcnksm/ghr
          ${GOPATH}/bin/ghr -n ${TAGNAME} -b "${TAGNAME}" -draft ${TAGNAME} dist/
